server:
  port: ${server.port:8080}   
 
spring:
  application:
    name: property-service    # change per service
  datasource:
    url: ${db_url}            # injected from Vault
    username: ${db_username}  # injected from Vault
    password: ${db_password}  # injected from Vault
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
 
management:
  endpoints:
    web:
      exposure:
        include: health
eureka:
  client:
    enabled: false