name: Deploy Booking Service to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build microservice
        run: |
          cd immobilier/booking-service
          mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: booking-service-jar
          path: immobilier/booking-service/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: booking-service-jar

      - name: List downloaded files
        run: ls -l

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bookinservice'
          publish-profile: ${{ secrets.AZURE_BOOKIN_SERVICE_PUBLISH_PROFILE }}
          package: './booking-service-jar/*.jar'  